### ISSUE TITLE
julia language server crashes - cannot connect to linux server from windows

### ISSUE THREAD

**Issue by jmgnve** [JuliaEditorSupport/LanguageServer.jl#184]
Hi!

I have code on a linux server that I am editing on my local windows machine. The correct path to the folder I am working in is `\\unixhome\users\jmg\projects\ican\ican_sim`. I can reach it from windows explorer. It seems like the language server "cuts" or "misses" the first part `\\unixhome\`. Perhaps this is an issue with my machine, I cannot guarantee that it isn´t. Thanks for any help.

```
ERROR: LoadError: SystemError: unable to read directory users\jmg\projects\ican\ican_sim: Unknown error
Stacktrace:
 [1] #walkdir#12(::Bool, ::Bool, ::Core.#throw, ::Function, ::String) at .\file.jl:462
 [2] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServer.LanguageServerInstance) at C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\scripts\languageserver\packages\LanguageServer\src\provider_misc.jl:41
 [3] run(::LanguageServer.LanguageServerInstance) at C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:52
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\scripts\languageserver\main.jl, in expression starting on line 27
[Info  - 16:18:37] Connection to server got closed. Server will restart.
[Error - 16:18:37] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:816:25)
    at Object.dispose (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:66:35)
    at LanguageClient.handleConnectionClosed (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:1071:38)
    at LanguageClient.handleConnectionClosed (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\main.js:86:15)
    at closeHandler (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:1059:18)
    at CallbackList.invoke (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:178:36)
    at closeHandler (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:212:26)
    at CallbackList.invoke (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:178:36)
[Error - 16:18:37] Request textDocument/documentLink failed.
Error: Connection got disposed.
    at Object.dispose (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:816:25)
    at Object.dispose (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:66:35)
    at LanguageClient.handleConnectionClosed (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:1071:38)
    at LanguageClient.handleConnectionClosed (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\main.js:86:15)
    at closeHandler (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-languageclient\lib\client.js:1059:18)
    at CallbackList.invoke (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:178:36)
    at closeHandler (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:212:26)
    at CallbackList.invoke (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:114:39)
    at Emitter.fire (C:\Users\jmg\.vscode\extensions\julialang.language-julia-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:178:36)
```

**Comment by davidanthoff** [comment]
I'm 99% certain we don't handle those kind of paths properly. In fact, I think I almost tracked down a case where we don't handle normal windows paths properly :)

Thanks for the bug report, actually really good to be reminded about network paths while I'm trying to fix the other problem, given how closely they are related.

**Comment by jmgnve** [comment]
Tell me if there is something I can help with. I am not a very good julia programmer, so for actual coding I need some guidance. Nevertheless, I can always test the latest version.

**Comment by AmjadHD** [comment]
> In fact, I think I almost tracked down a case where we don't handle normal windows paths properly :)

yes normal windows path don't work wich means the goto defintion feature doesn't work:

for example when triggering goto definition for `println`:
`C::\\Users\\User\\AppData\\Local\\Julia-0.6.2\\share\\julia\\base\\coreio.jl`
Note the extra colon.

**Comment by davidanthoff** [comment]
I think the broader strategy should be to use https://github.com/rofinn/FilePaths.jl, and keep adding the missing features there (e.g. it also doesn't support network paths right now, but it probably makes more sense to add support in FilePaths.jl and then just have things work here).
